# Generated by Django 3.2.3 on 2021-05-28 15:48

import config.asset_storage
from django.db import migrations, models
import meme.utils
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tag", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Meme",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        storage=config.asset_storage.ImageStorage,
                        upload_to=meme.utils.upload_image,
                    ),
                ),
                ("recommended", models.IntegerField(default=0)),
                ("description", models.CharField(max_length=255)),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created_at"),
                ),
                ("tags", models.ManyToManyField(to="tag.Tag")),
            ],
            options={
                "ordering": ["recommended"],
            },
        ),
    ]
