# Generated by Django 3.2.3 on 2021-05-25 17:17

import config.asset_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meme", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="meme",
            name="image_access_path",
        ),
        migrations.AlterField(
            model_name="meme",
            name="image",
            field=models.ImageField(
                storage=config.asset_storage.ImageStorage, upload_to=""
            ),
        ),
    ]
